# Deployment descriptor example for GKE
apiVersion: v1
kind: Service
metadata:
  name: slanger
  labels:
    run: slanger
spec:
  type: LoadBalancer
  ports:
    - port: 4567
      targetPort: 4567
      protocol: TCP
      name: api
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: ws
  selector:
    run: slanger
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slanger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: slanger
    spec:
      containers:
        - name: redis
          image: redis
        - name: slanger
          image: gcr.io/plasma-column-128721/slanger-0.0.1
          env:
            - name: APP_KEY
              value: cf256b0f27ce65f518c1
            - name: SECRET
              value: 49c7e5564de31d764400
					args:
						- "--webhook_url=https://srs-wfm-staging.herokuapp.com/v1/pusher/clientEvent"
          ports:
          	- containerPort: 4567
          	- containerPort: 8080

